### ISSUE TITLE
ImportError: No module named wham_project.wham

### ISSUE THREAD

**Issue by andybak** [mbylstra/django-graphql#1]
```
 > git clone etc
 > pip install -r requirements.txt
[all ok]

> python scratchpad.py 
ImportError: No module named wham_project.wham
```

**Comment by mbylstra** [comment]
Hi Andy,

This project was a quick thing I made the weekend after GraphQL was announced at React Conf. It's not in a very usable state and is based on the very small amount of information that's available about GraphQL. I had an  idea to integrate it with Django Wham (a different project connects to Rest APIs), but I never finished that part and must have left an unused import statement in. If I were you I would wait till this Thursday, as I think there's a good chance GraphQL will be officially launched at React Europe. This code will probably become obsolete then :)

**Comment by andybak** [comment]
Fair enough. I thought it was interesting in it's own right but you make a good point.
